### ISSUE TITLE
OSX autostart plist

### ISSUE THREAD

**Issue by SJ50** [StareInTheAir/mpv-trakt-sync-daemon#1]
create file "org.mpvtraktsync.plist" in "~/Library/LaunchAgents/" with following content
edit **/Path/To/**

````
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
    "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>org.user.mpvtraktsync</string>
    <key>ProgramArguments</key>
    <array>
        <string>**/Path/To/**mpv-trakt-sync-daemon/venv/bin/python3</string>
        <string>sync_daemon.py</string>
    </array>
    <key>WorkingDirectory</key>
    <string>**/Path/To/**mpv-trakt-sync-daemon</string>
    <key>RunAtLoad</key>
    <true />
    <key>LaunchOnlyOnce</key>
    <true />
    <key>KeepAlive</key>
    <true />
</dict>
</plist>
````

execute following command in terminal
`launchctl load ~/Library/LaunchAgents/org.mpvtraktsync.plist`
verify by running following command
`launchctl list | grep org.user.mpvtraktsync`

**Comment by StareInTheAir** [comment]
Thank you. Added in 4ea89630f62839f995f3cd2554495f1d9b66170e. If you use a [pull request](https://help.github.com/articles/about-pull-requests/) next time, it's less work for me.
