### ISSUE TITLE
guessit 3.0.3 can't guess tv episodes correctly

### ISSUE THREAD

**Issue by lldsolitude** [StareInTheAir/mpv-trakt-sync-daemon#11]
guessit 3.0.3 can't guess tv episodes named XXX.SxxExx.720p.HDTV.x264-XXX.mkv correctly, the result being a movie titled "XXX SxxExx". Updating to guessit 3.1.0 solved the problem. Therefore requirements.txt and requirements-win.txt should be updated.

**Comment by Alistair1231** [comment]
Thanks!

**Comment by StareInTheAir** [comment]
Fixed in 9656e3e
