### ISSUE TITLE
Python 3.7 Support

### ISSUE THREAD

**Issue by kremfloete** [StareInTheAir/mpv-trakt-sync-daemon#2]
This project currently doesn't support Python 3.7 because 'trakt_key_holder.pyc' was compiled with Python 3.6 and the source isn't available. It can be decompiled by the user to make it work, but that seems a bit impractical.

**Comment by StareInTheAir** [comment]
Should fixed with acef0c6d15f3325d8dddad3644473443aad6876e. Please comment if not.
